# This is a basic workflow to help you get started with Actions

name: backend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [BE/dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [12.x]
    defaults:
      run:
        working-directory: ./backend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install
      - name: run test
        run: npm run test
        env:
          PORT: 3000
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: 3306
          DB_DIALECT: mysql
          GITHUB_ID: test
          GITHUB_SECRET: test
          JWT_SECRET: test
          SERVER_URL: test
