name: frontend

on:
  pull_request:
    types: [closed] # when PR closed
    branches: [FE/dev]

jobs:
  build:
    runs-on: [ubuntu-latest]
    if: github.event.pull_request.merged
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            bash deploy.sh
