name: frontend

on:
  push:
    branches: [FE/dev]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: executing client server
        uses: shellboy/ssh-action@master
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            bash deploy.sh
