name: iOS

on:
  pull_request:
    branches: [ iOS ]

jobs:
  build:
    runs-on: macOS-latest
    env: 
      XC_VERSION: ${{ '12.1' }} 
      XC_WORKSPACE: ${{ 'IssueTracker.xcworkspace' }} 
      XC_SCHEME: ${{ 'IssueTracker' }}

    steps:
      - name: Select Xcode Version 
        run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
        
      - uses: actions/checkout@v2
        
      - name: Install Dependency
        working-directory: ./iOS/IssueTracker
        run: "pod install --repo-update --clean-install"

      - name: Run Unit and UI Tests
        working-directory: ./iOS/IssueTracker
        run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 12'

